language: php

php:
  - 7.1.9

before_install:
  - cp .env.travis .env
  - mysql -e 'CREATE DATABASE soen343;'

install:
  - composer install
  - composer update
  - php artisan key:generate

script:
  - vendor/bin/phpunit

services:
  - mysql

notifications:
  email: false